title: Jiratown Architecture {
  near: top-center
  shape: text
  style: {
    font-size: 29
    bold: true
    underline: true
  }
}

tracker: Tracker {
  parser: User-Prompt Parser
  prompt: Prompt Engineer

  parser -> prompt
}

workflow: Workflow {
  harness: Harness {
    plugin: Agent Plugin {
      mcp: MCP
      hooks: Hooks
      tools: Tools
      lsp: LSPs
      models: Models
      agents: Agents
      skills: Skills
      commands: Commands
      monitors: Monitors
      dependencies: Dependencies
    }
  }

  services: Services {
    style: {
      stroke-dash: 3
    }
    monitor: MonitorService {
      remote: Remote Polling
      local: Local File / Script Monitoring
    }
    memory: MemoryService {
      cache: Cache {
        l1: L1 - context.md
        l2: L2 - retriv (hybrid search)
      }
      events: System Events
      notifications: System Notifications
    }
  }

  services.monitor -> harness
  services.memory <-> harness
}

claude: Claude Code
opencode: Opencode

plugin: Plugins

github: Github Plugin
jira: Jira Plugin

tracker -> workflow
tracker.prompt <- workflow.services.memory

claude -> workflow.harness
opencode -> workflow.harness

jira -> plugin
github -> plugin

plugin -> tracker: {
  style.stroke-dash: 3
}

plugin -> workflow: {
  style.stroke-dash: 3
}

plugin -> workflow.*: {
  style.stroke-dash: 3
}