import { describe, expect, it } from "vitest";

import {
  METADATA_FOOTER,
  WORKHORSE_MARKER,
  isWorkhorseGenerated,
  withWorkhorseFooter,
} from "../metadata-footer";

describe("metadata-footer", () => {
  describe("withWorkhorseFooter", () => {
    it("appends footer to plain text", () => {
      const body = "Hello, world!";
      const result = withWorkhorseFooter(body);

      expect(result).toBe(body + METADATA_FOOTER);
      expect(result).toContain(WORKHORSE_MARKER);
    });

    it("is idempotent - does not add footer twice", () => {
      const body = "Hello, world!";
      const withFooter = withWorkhorseFooter(body);
      const withFooterAgain = withWorkhorseFooter(withFooter);

      expect(withFooterAgain).toBe(withFooter);
      // Should only have one occurrence of the marker
      const markerRegex = new RegExp(
        WORKHORSE_MARKER.replace(/[[\]]/g, "\\$&"),
        "g",
      );
      expect(withFooterAgain.match(markerRegex)?.length).toBe(1);
    });

    it("detects footer anywhere in the body", () => {
      const bodyWithFooterInMiddle = `Start\n\n${WORKHORSE_MARKER} agent\n\nEnd`;
      const result = withWorkhorseFooter(bodyWithFooterInMiddle);

      expect(result).toBe(bodyWithFooterInMiddle);
    });
  });

  describe("isWorkhorseGenerated", () => {
    it("returns true for content with the marker", () => {
      const body = `Hello!\n\n---\n<sub>🤖 _${WORKHORSE_MARKER}(https://github.com/StevenJPx2/workhorse) agent_</sub>`;
      expect(isWorkhorseGenerated(body)).toBe(true);
    });

    it("returns false for content without the marker", () => {
      const body = "Hello, world!";
      expect(isWorkhorseGenerated(body)).toBe(false);
    });

    it("returns true for content generated by withWorkhorseFooter", () => {
      const body = withWorkhorseFooter("Hello!");
      expect(isWorkhorseGenerated(body)).toBe(true);
    });
  });

  describe("METADATA_FOOTER", () => {
    it("contains expected content", () => {
      expect(METADATA_FOOTER).toContain("Workhorse");
      expect(METADATA_FOOTER).toContain("github.com");
      expect(METADATA_FOOTER).toContain(WORKHORSE_MARKER);
    });
  });
});
