// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat.post').default>>>>
    }
    '/api/tickets/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tickets/[id].get').default>>>>
    }
    '/api/tickets/:id/activity': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tickets/[id]/activity.get').default>>>>
    }
    '/api/tickets/:id/diff': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tickets/[id]/diff.get').default>>>>
    }
    '/api/tickets/:id/stop': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tickets/[id]/stop.post').default>>>>
    }
    '/api/tickets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tickets/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tickets/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}