/**
 * Adapter context types.
 *
 * @module workflow/orchestrator/types/adapter-context
 */

import type { Emitter } from "mitt";
import type { Database, Issue } from "#db";
import type { HookEventMap } from "#lib/hooks";
import type { MemoryService } from "#services/memory";
import type { OrchestratorTool } from "./tools.ts";

/**
 * Context passed to adapter constructors.
 *
 * Contains everything an adapter needs to start an agent session:
 * - Issue information
 * - Worktree path
 * - System prompt and initial message
 * - Registered tools to translate
 * - Service references for tool execution
 */
export interface AdapterContext {
  /** Issue the agent will work on */
  issue: Issue;

  /** Path to the git worktree */
  worktreePath: string;

  /**
   * System prompt to use.
   * Generated by PromptEngineer.buildHybridPrompt().
   * Includes tool descriptions so agent knows what's available.
   */
  systemPrompt: string;

  /**
   * Initial message to send to the agent.
   * Generated by PromptEngineer.buildHybridPrompt().
   * Contains task description and any pending notifications.
   */
  initialMessage: string;

  /**
   * Registered tools to make available to the agent.
   * Adapter translates these to native format (e.g., pi ExtensionFactory).
   */
  tools: OrchestratorTool[];

  /** Database access for tool execution */
  db: Database;

  /** Hook emitter for events */
  hooks: Emitter<HookEventMap>;

  /** Memory service access */
  memory: MemoryService;

  /** Model to use (optional, harness-specific) */
  model?: string;
}
