/**
 * Metadata footer for comments and PRs created by Workhorse.
 *
 * Appends a small, unobtrusive footer that identifies the content as
 * machine-generated by a Workhorse agent.
 *
 * @module workhorse-core/lib/metadata-footer
 */

const WORKHORSE_FOOTER = `\n\n---\n<sub>🤖 _Posted by [Workhorse](https://github.com/anthropics/workhorse) agent_</sub>`;

/**
 * Append the Workhorse metadata footer to a message body.
 * Use for comments and PR descriptions to identify agent-generated content.
 */
export function withWorkhorseFooter(body: string): string {
  return body + WORKHORSE_FOOTER;
}

/**
 * The raw footer string (for ADF or other custom formatting needs).
 */
export const METADATA_FOOTER = WORKHORSE_FOOTER;
