/**
 * Metadata footer for comments and PRs created by Workhorse.
 *
 * Appends a small, unobtrusive footer that identifies the content as
 * machine-generated by a Workhorse agent.
 *
 * @module workhorse-core/lib/metadata-footer
 */

/**
 * Marker string to identify Workhorse-generated content.
 * Note: Must work after markdown→ADF→plaintext round-trip where link brackets are stripped.
 */
export const WORKHORSE_MARKER = "Posted by Workhorse";

const WORKHORSE_FOOTER = `\n\n---\n<sub>🤖 _${WORKHORSE_MARKER} agent_ · [repo](https://github.com/StevenJPx2/workhorse)</sub>`;

/**
 * Check if content was generated by Workhorse (contains the marker).
 * Use this to filter out bot-generated comments in monitors.
 */
export function isWorkhorseGenerated(body: string): boolean {
  return body.includes(WORKHORSE_MARKER);
}

/**
 * Append the Workhorse metadata footer to a message body.
 * Use for comments and PR descriptions to identify agent-generated content.
 * Idempotent: won't add the footer if it's already present.
 */
export function withWorkhorseFooter(body: string): string {
  if (isWorkhorseGenerated(body)) {
    return body;
  }
  return body + WORKHORSE_FOOTER;
}

/**
 * The raw footer string (for ADF or other custom formatting needs).
 */
export const METADATA_FOOTER = WORKHORSE_FOOTER;
